INSERT INTO especialidades (nombre) VALUES
('Acompañamiento en enfermedad'),
('Adicciones'),
('Ansiedad'),
('Ansiedad social'),
('Ataques de pánico'),
('Autoestima'),
('Control de impulsos'),
('Depresión'),
('Duelo'),
('Estrés y burnout'),
('Fobias'),
('Sexualidad'),
('TDAH'),
('TOC'),
('Terapia de pareja'),
('Terapia infantil'),
('Trastornos alimentarios'),
('Trastornos del sueño'),
('Trauma');

INSERT INTO psicologos (nombre, email, telefono, especialidades, bio) VALUES
('Marta Ibáñez', 'marta.ibanez@ejemplo.com', '+34 611 222 333', 'Depresión,Duelo,Trauma', 'Trabajo desde un enfoque cercano y sin prisas, acompañando procesos de pérdida y duelo. Más de diez años ayudando a personas a atravesar momentos difíciles.'),
('Diego Fonseca', 'diego.fonseca@ejemplo.com', '+34 622 333 444', 'Ansiedad,Estrés y burnout,Trastornos del sueño', 'Especializado en ansiedad y estrés laboral. Utilizo herramientas prácticas para que notes cambios desde las primeras sesiones.'),
('Laura Campos', 'laura.campos@ejemplo.com', '+34 633 444 555', 'Terapia de pareja,Autoestima', 'Acompaño a parejas e individuos a mejorar su comunicación y su relación consigo mismos, en un espacio sin juicios.'),
('Marta Sánchez', 'marta.sanchez@ejemplo.com', '+34 644 555 666', 'Trastornos alimentarios,Autoestima', 'Trabajo con un enfoque integrador para trastornos de la conducta alimentaria y la imagen corporal, desde la autocompasión.'),
('Javier Romero', 'javier.romero@ejemplo.com', '+34 655 666 777', 'Adicciones,Control de impulsos', 'Especialista en adicciones y control de impulsos, con un enfoque práctico y sin juicios.'),
('Elena Vidal', 'elena.vidal@ejemplo.com', '+34 666 777 888', 'Ansiedad,Fobias,Ataques de pánico', 'Uso técnicas de exposición gradual y respiración para reducir crisis de ansiedad y fobias.'),
('Rubén Castillo', 'ruben.castillo@ejemplo.com', '+34 677 888 999', 'Terapia infantil,TDAH', 'Trabajo con niños y adolescentes en problemas de conducta y TDAH junto con sus familias.'),
('Sofía Navarro', 'sofia.navarro@ejemplo.com', '+34 688 999 000', 'Trastornos del sueño,Ansiedad', 'Combino técnicas de higiene del sueño y manejo del estrés para mejorar el descanso.'),
('Pablo Herrera', 'pablo.herrera@ejemplo.com', '+34 699 000 111', 'Trauma,Duelo', 'Especializado en trauma y EMDR, acompañando procesos de recuperación a tu propio ritmo.'),
('Isabel Domínguez', 'isabel.dominguez@ejemplo.com', '+34 610 111 222', 'Autoestima,Ansiedad social', 'Ayudo a construir una autoestima sólida y a superar la ansiedad en las relaciones sociales.'),
('Andrés Molina', 'andres.molina@ejemplo.com', '+34 621 222 333', 'Estrés y burnout', 'Trabajo con profesionales que sienten agotamiento y quieren recuperar el equilibrio.'),
('Cristina Ortega', 'cristina.ortega@ejemplo.com', '+34 632 333 444', 'Depresión,Duelo', 'Acompaño con empatía procesos de tristeza profunda y pérdida hacia una vida con sentido.'),
('Miguel Ángel Torres', 'miguelangel.torres@ejemplo.com', '+34 643 444 555', 'Terapia de pareja,Sexualidad', 'Especialista en terapia de pareja y sexualidad, con un enfoque respetuoso y directo.'),
('Paula Cabrera', 'paula.cabrera@ejemplo.com', '+34 654 555 666', 'Ansiedad,TOC', 'Trabajo con TOC y ansiedad usando terapia cognitivo-conductual basada en evidencia.'),
('Natalia Reyes', 'natalia.reyes@ejemplo.com', '+34 676 777 888', 'Terapia infantil,Ansiedad', 'Especialista en psicología infantil, ayudo a niños a gestionar sus emociones de forma sana.'),
('Beatriz Serrano', 'beatriz.serrano@ejemplo.com', '+34 698 999 000', 'Duelo,Acompañamiento en enfermedad', 'Ofrezco un espacio seguro para procesar pérdidas y enfermedades con calma y respeto.');

INSERT INTO psicologo_especialidad (psicologo_id, especialidad_id) VALUES
(1, 8), (1, 9), (1, 19),
(2, 3), (2, 10), (2, 18),
(3, 6), (3, 15),
(4, 6), (4, 17),
(5, 2), (5, 7),
(6, 3), (6, 5), (6, 11),
(7, 13), (7, 16),
(8, 3), (8, 18),
(9, 9), (9, 19),
(10, 4), (10, 6),
(11, 10),
(12, 8), (12, 9),
(13, 12), (13, 15),
(14, 3), (14, 14),
(15, 3), (15, 16),
(16, 1), (16, 9);

