INSERT INTO ciudades
(id,ciudades,país,continente)
VALUES
(NULL,"Sete Lagoas","Brasil","América del Sur"),
(NULL,"São Paulo","Brasil","América del Sur"),
(NULL,"Río de Janeiro","Brasil","América del Sur"),
(NULL,"Belo Horizonte","Brasil","América del Sur"),
(NULL,"Buenos Aires","Argentina","América del Sur"),
(NULL,"Córdoba","Argentina","América del Sur"),
(NULL,"Santiago","Chile","América del Sur"),
(NULL,"Lima","Perú","América del Sur"),
(NULL,"Bogotá","Colombia","América del Sur"),
(NULL,"Medellín","Colombia","América del Sur"),
(NULL,"Montevideo","Uruguay","América del Sur"),
(NULL,"Quito","Ecuador","América del Sur"),
(NULL,"Caracas","Venezuela","América del Sur"),
(NULL,"Ciudad de México","México","América del Norte"),
(NULL,"Guadalajara","México","América del Norte"),
(NULL,"Nueva York","Estados Unidos","América del Norte"),
(NULL,"Los Ángeles","Estados Unidos","América del Norte"),
(NULL,"Chicago","Estados Unidos","América del Norte"),
(NULL,"Toronto","Canadá","América del Norte"),
(NULL,"Montreal","Canadá","América del Norte"),
(NULL,"La Habana","Cuba","América Central"),
(NULL,"San José","Costa Rica","América Central"),
(NULL,"Ciudad de Panamá","Panamá","América Central"),
(NULL,"Madrid","España","Europa"),
(NULL,"Barcelona","España","Europa"),
(NULL,"Valencia","España","Europa"),
(NULL,"Sevilla","España","Europa"),
(NULL,"Lisboa","Portugal","Europa"),
(NULL,"Oporto","Portugal","Europa"),
(NULL,"París","Francia","Europa"),
(NULL,"Roma","Italia","Europa"),
(NULL,"Milán","Italia","Europa"),
(NULL,"Berlín","Alemania","Europa"),
(NULL,"Londres","Reino Unido","Europa"),
(NULL,"Ámsterdam","Países Bajos","Europa"),
(NULL,"Atenas","Grecia","Europa"),
(NULL,"Tokio","Japón","Asia"),
(NULL,"Pekín","China","Asia"),
(NULL,"Shanghái","China","Asia"),
(NULL,"Seúl","Corea del Sur","Asia"),
(NULL,"Bombay","India","Asia"),
(NULL,"Bangkok","Tailandia","Asia"),
(NULL,"Estambul","Turquía","Asia"),
(NULL,"El Cairo","Egipto","África"),
(NULL,"Lagos","Nigeria","África"),
(NULL,"Nairobi","Kenia","África"),
(NULL,"Ciudad del Cabo","Sudáfrica","África"),
(NULL,"Casablanca","Marruecos","África"),
(NULL,"Sídney","Australia","Oceanía"),
(NULL,"Auckland","Nueva Zelanda","Oceanía");
